name: Render App Keep-Alive

on:
  schedule:
    - cron: '*/10 2-16 * * *' # Every 10 minutes from 2:00 AM to 4:50 PM UTC (7:30 AM to 10:20 PM IST)
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    
    steps:
    - name: Ping API Endpoint
      run: |
        curl -s -f -o /dev/null -w "%{http_code}" https://ecommerce-rec-engine.onrender.com/health
